### ISSUE TITLE
Ad failure to load after mAdsManager.init() the onAdEvent or onAdError will not fire

### ISSUE THREAD

**Issue by atentis** [googleads/googleads-ima-android#40]
At random the mAdsManager.init() will fire but sometimes there will be no response from onAdEvent or onAdError so ad just fails to load and user gets a black screen. Since onAdError doesnt hit there is no way to handle this issue as a developer. 

I have confirmed this issue on below devices using the latest SDK and multiple ad tags from different providers:

- Shield Android TV (more frequently than others)
- Amazon Fire TV Stick 
- Amazon Fire TV 2nd gen
- Sony Bravia Android TV
- Android Studio Android TV emulator
- Google ADT-2 
- Pixel 3

The issue has been reported in three different threads on the IMA SDK product forum.
https://groups.google.com/forum/#!topic/ima-sdk/sR4K4UMWcCU
https://groups.google.com/forum/#!topic/ima-sdk/rRAEtBZAGz4
https://groups.google.com/forum/#!topic/ima-sdk/_h74a6IDgaM

Any help or escalation on this issue would be greatly appreciated as I have had to turn off IMA sdk on my app due to user complaints.

**Comment by atentis** [comment]
Another report on S.O. https://stackoverflow.com/questions/55034660/ima-sdk-issue-on-android

**Comment by atentis** [comment]
Another report: https://groups.google.com/d/msg/ima-sdk/ayvmLfwSqYE/RMCw6Q66BgAJ

**Comment by Kiro705** [comment]
Hello @atentis ,

Since this issue is not specific to the IMA sample apps, I would recommend working through the IMA technical forum (https://groups.google.com/g/ima-sdk), which I see you had been doing in the past.

With that in mind, I do not believe that there is currently an active issue for on the forum. If the issue is still happening for you, I would recommend creating a new post there.
