### ISSUE TITLE
Saving advertising information when rotate

### ISSUE THREAD

**Issue by Miklesam** [googleads/googleads-ima-android#69]
Hello, in the Basic Example, the manifest contains:
android parameter: configChanges = "orientation", so when rotate, views does not recreating.

In my case, without android parameter: configChanges = "orientation".  When I rotate the screen, I lose information about the advertisement. 

Here is a video with the described behavior:

https://user-images.githubusercontent.com/22328501/122373517-36ee4500-cf6a-11eb-86e1-8d1e89051b05.mp4

To solve the problem, I save playerView and add it to container when views recreate.

(viewModel.playerView?.parent as ViewGroup).removeView(viewModel.playerView)
 findViewById<FrameLayout>(R.id.container).addView(viewModel.playerView)

Looks like that:

https://user-images.githubusercontent.com/22328501/122374205-d6133c80-cf6a-11eb-875f-57a5d9a005c9.mp4

Here's a repository with an example described 
https://github.com/Miklesam/IMA-SDK-Rotate

Please tell me if this is the correct way to save information about an advertisement when rotate the phone. Or is there a more correct and elegant way?

Thanks for all your help.

**Comment by Kiro705** [comment]
Hello @Miklesam ,

I believe that the method you are using to handle device rotation, may lead to issues related to IMA signaling. It is not recommended move/change views once IMA has been initiated. It may have negative effects for ad impressions and signaling.

I would recommend using `android parameter: configChanges = "orientation"` to handle device rotations.

However, since this issue is not specific to the Android samples, you may be able to receive more specific help by raising your issue on the [IMA technical forum](https://groups.google.com/g/ima-sdk/).

Please feel free to reopen this issue if you have farther questions
